# Generated by Django 6.0.3 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_update_status_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparing", "상품 준비 중"),
                    ("shipping", "배송 중"),
                    ("delivered", "배송 완료"),
                    ("exchange_requested", "교환 접수"),
                    ("cancelled", "주문 취소"),
                    ("refunded", "환불 완료"),
                ],
                default="preparing",
                max_length=20,
            ),
        ),
    ]
