export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({ children }) {
  return (

    <section className="auth-wrapper">
      {children}
    </section>
  )
}