# Generated by Django 6.0.3 on 2026-03-10 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("pending", "결제 대기"), ("paid", "결제 완료")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparing", "상품 준비 중"),
                    ("shipping", "배송 중"),
                    ("delivered", "배송 완료"),
                    ("cancelled", "주문 취소"),
                    ("refunded", "환불 완료"),
                ],
                default="preparing",
                max_length=20,
            ),
        ),
    ]
