
from typing import TypedDict, List, Annotated
import operator
from langchain_core.messages import BaseMessage

def merge_messages(left: List[BaseMessage], right: List[BaseMessage]) -> List[BaseMessage]:
    """Append messages."""
    return left + right

class AgentState(TypedDict):
    """The state of the agent."""
    question: str
    # Messages have the type "list". The `add_messages` function
    # in the annotation defines how this state key should be updated
    # (in this case, it appends messages to the list, rather than overwriting them)
    messages: Annotated[List[BaseMessage], merge_messages]
    documents: List[str]  # Retrieved context chunks
    generation: str       # The final answer generated by the LLM
