
from typing import TypedDict, List, Annotated, Optional, Dict, Any
import operator
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

# OrderInfo as a Dict for slot information
OrderInfo = Dict[str, Any]

class AgentState(TypedDict):
    """The state of the agent."""
    question: str
    # Messages have the type "list". The `add_messages` function
    # in the annotation defines how this state key should be updated
    # (in this case, it appends messages to the list, rather than overwriting them)
    messages: Annotated[List[BaseMessage], add_messages]
    documents: List[str]  # Retrieved context chunks
    generation: str       # The final answer generated by the LLM
    
    # New fields for state management
    current_intent: Optional[str]  # Detected intent
    order_slots: OrderInfo         # Slot information for orders
    missing_slot: Optional[str]    # Missing information needed
